version: "3.9"
volumes:
  app_db:
services:
  web:
    build: ./src/MoserBlog.Web
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    volumes:
      - app_db:/var/opt/mssql
    environment:
        SA_PASSWORD: ""
        ACCEPT_EULA: "Y"