version: "3.9"
volumes:
  app_db:
services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5112:80"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      mediatool:
        condition: service_started
    links:
      - "db:localdatabase"

  mediatool:
    image: "philippmos/moserblog-mediatool:3113"
    ports:
      - "5113:80"
    env_file:
      - .env

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    volumes:
      - app_db:/var/opt/mssql
    env_file:
      - .env
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s