version: "3.9"
volumes:
  app_db:
services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - .env
    links:
      - "db:localdatabase"

  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    volumes:
      - app_db:/var/opt/mssql
    env_file:
      - .env