trigger:
- main
- develop

- feature/*
- release/*


variables:
  tag: '$(Build.BuildId)'
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

resources:
- repo: self


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

- stage: Publish
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  displayName: Publish
  jobs:
    - job: Publish
      displayName: Publish
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker Hub'
          repository: 'philippmos/moserblog-web'
          command: 'push'
